import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'

const Grid = dynamic(() => import('./components/Grid'), {
  ssr: false,
})

import { useState, useEffect, useRef } from 'react'
import Pusher from "pusher-js"
import axios from "axios"

export default function Home() {
  let pusher = useRef(null)
  

  const cells = []
    for (let x = 0; x < 20; x++) {
      for (let y = 0; y < 20; y++) {
        cells.push({
          id: `${x}-${y}`,
          //x: x,
          //y: y,
          value: "FFFFFF",
        })
      }
    }
  //const [grid, setGrid] = useLocalStorage('grid', cells)
  const [grid, setGrid] = useState(cells)

  async function handleClick(cell) {
    await axios.post("/api/cell", {
      cell,
    })
  }

  function onPusherEvent(data) {
    console.log('grid after click', grid.slice(0, 5))
      const newGrid = grid.map((cell) => {
        if (cell.id === data.cell.id) {
          return { ...cell, value: data.cell.value }
        } else {
          return { ...cell }
        }
      })
      console.log('newGrid', newGrid.slice(0, 5))
      setGrid(newGrid)
  }

  useEffect(() => {
    pusher = new Pusher('11556dc9c381feb5b9f7', {
      cluster: 'us3',
      encrypted: true
    })
    const channel = pusher.subscribe('drawer-channel')
    channel.bind("drawer-event", async (data) => {
      onPusherEvent(data)
    })

    return () => {
      channel.unbind_all()
      channel.unsubscribe()
    }
  }, [onPusherEvent])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Drawer: <br /> Draw Whatever <br />🖌
        </h1>
        <Grid grid={grid} handleClick={handleClick} />
      </main>
    </div>
  )
}

function useLocalStorage(key, initialValue) {
  // State to store our value
  // Pass initial state function to useState so logic is only executed once
  const [storedValue, setStoredValue] = useState(() => {
    if (typeof window === "undefined") {
      return initialValue;
    }

    try {
      // Get from local storage by key
      const item = window.localStorage.getItem(key);
      // Parse stored json or if none return initialValue
      return item ? JSON.parse(item) : initialValue;
    } catch (error) {
      // If error also return initialValue
      console.log(error);
      return initialValue;
    }
  });

  // Return a wrapped version of useState's setter function that ...
  // ... persists the new value to localStorage.
  const setValue = (value) => {
    try {
      // Allow value to be a function so we have same API as useState
      const valueToStore =
        value instanceof Function ? value(storedValue) : value;
      // Save state
      setStoredValue(valueToStore);
      // Save to local storage
      if (typeof window !== "undefined") {
        window.localStorage.setItem(key, JSON.stringify(valueToStore));
      }
    } catch (error) {
      // A more advanced implementation would handle the error case
      console.log(error);
    }
  };

  return [storedValue, setValue];
}
