import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'

const Grid = dynamic(() => import('./components/Grid'), {
  ssr: false,
})

import axios from "axios"

export default function Home() {

  async function handleClick(cell) {
    await axios.post("/api/cell", {
      cell,
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Drawer: <br /> Draw Whatever <br />🖌
        </h1>
        <Grid handleClick={handleClick} />
      </main>
    </div>
  )
}

